### ISSUE TITLE
undefined method `to_json' for #<Hash:0x00007feef68b0d48> (NoMethodError)

### ISSUE THREAD

**Issue by zsan** [lorismaz/csiconnect#1]
I have script like:

```
require 'yaml'
require 'csiconnect'
require 'byebug'
config = YAML.load_file 'config/gvc_credentials.yml'

Csiconnect.api_base_url = config["gvc_url"]
Csiconnect.username  = config["gvc_username"]
Csiconnect.password  = config["gvc_password"]

response = Csiconnect::Token.create
puts "#{response['token']}"
```

and i got

```
Traceback (most recent call last):
  2: from bin/gvc_token_generator.rb:12:in `<main>'
  1: from /Users/zak/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/csiconnect-a0ce6ad005b0/lib/csiconnect/token.rb:7:in `create'
/Users/zak/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/csiconnect-a0ce6ad005b0/lib/csiconnect.rb:85:in `request': undefined method `to_json' for #<Hash:0x00007feef68b0d48> (NoMethodError)
Did you mean?  to_s
Dians-MacBook-Pro-2:usa-esta-connector zak$ vim /Users/zak/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/csiconnect-a0ce6ad005b0/lib/csiconnect.rb
Dians-MacBook-Pro-2:usa-esta-connector zak$ vim /Users/zak/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/csiconnect-a0ce6ad005b0/lib/csiconnect.rb
```

I think you need to `require "json"` in the top of the library to use `to_json`

**Comment by kevinhq** [comment]
@zsan - please try again, and let me know if it works

**Comment by zsan** [comment]
It worked, thank you.
